### ISSUE TITLE
When to update?

### ISSUE THREAD

**Issue by forence** [sgrvinod/Deep-Tutorials-for-PyTorch#1]
Hi, thanks for your repo on some difficult but interesting problems. It's very helpful to my job! We're looking forward to your updata.

**Comment by sgrvinod** [comment]
Thank you very much! Sorry, I've been busy, I'm continuing to work on the tutorials now. The object detection tutorial should be up by the first week of February, and the text classification in two weeks after that.

**Comment by forence** [comment]
I'm happy to hear that, good job 👍
